describe("backend_list_versions", function()
    describe("PLUGIN:BackendListVersions", function()
        pending("integration test: should return empty versions for non-postgres tools")
        pending("integration test: should fetch versions from GitHub API")
        pending("integration test: should filter by minimum major version")
    end)
end)
